### PR TITLE
fix bug #188

### PR DESCRIPTION
**Pull request by whuream**
fix bug #188 
and a bug Non-ASCII in url attribute causes encode error

### CODE REVIEW

**Comment by Alir3z4** [comment]
@whuream CI job has failed, the only python version that passed is 2.6.
Please have a look at https://travis-ci.org/Alir3z4/html2text/builds/295721714

**Comment by Alir3z4** [comment]
@whuream thanks for the patch.
I'll merged it in master and will cut a release soon.

**Comment by tastynachos** [comment]
@Alir3z4 any plans for a cut soon? I just traced a bug back in one of my applications to to #188/#190 I don't see the fix for it in master yet

**Comment by Alir3z4** [comment]
@tastynachos Sorry for the delayed release.
I was waiting to get some other pull requests in.

The new release will be out today.

**Comment by tastynachos** [comment]
@Alir3z4 Thanks I just grabbed it and it fixed the issue I was seeing on my side! Thank you for all your work

**Comment by Alir3z4** [comment]
@tastynachos sure, thanks for reminding me.
Happy hacking ;)

**Pull request merged**
