### PR TITLE
Don't add line breaks inside link names

### PR DESCRIPTION
**Pull request by mborsetti**
The following HTML code
```
<a href="http://example.com" title="MyTitle"> first example</a>
<br>
<a href="http://example.com" ><p> second example</p></a>
```

is being converted by `html2text` version (2020, 1, 16) to the following Markdown (notice in the second example the line break before the closing `]`):
```
[ first example](http://example.com "MyTitle")  

[ second example

](http://example.com)
```

or with inline_links = False:
```
[ first example][1]  

[ second example

][2]

   [1]: http://example.com (MyTitle)

   [2]: http://example.com
```

The additional line break, besides looking askew, doesn't seem to be allowed by the official [specs](https://daringfireball.net/projects/markdown/syntax#link), and indeed breaks converting Markdown back to HTML.

This PR fixes the code to produce the following **correct** Markdown:
```
[ first example](http://example.com "MyTitle")  
[ second example](http://example.com)
```

or with inline_links = False:
```
[ first example][1]  
[ second example][2]

   [1]: http://example.com (MyTitle)

   [2]: http://example.com
```

Python 3.9 code to replicate the above:
```
import html2text
print(f'{html2text.__version__=}')
data = ('<a href="http://example.com" title="MyTitle"> first example</a>\n'
        '<br>\n'
        '<a href="http://example.com" ><p> second example</p></a>')
parser = html2text.HTML2Text()
markdown = parser.handle(data)
print(markdown)
parser.inline_links = False
markdown = parser.handle(data)
print(markdown)
```

### CODE REVIEW

**Comment by Alir3z4** [comment]
@mborsetti Thanks for taking care of it.

The code looks good to me, however it'd be much  better if we could add some documentation on the code changes to understand them, basically "Why" part of the documentation.

**Comment by mborsetti** [comment]
@Alir3z4 Sorry I am new to contributing to the project, and the only documentation I see is `usage.md`, which is pretty minimal.  What do you have in mind?  Feel free to edit my PR at will if that's easier.

**Comment by mborsetti** [comment]
@Alir3z4 is there anything else you need from me before accepting this PR?

Markdown does not allow for breaks inside link names (between `[` and `]`), and they (obviously) break any Markdown to HTML parser such as [markdown2](https://pypi.org/project/markdown2/) used in my project [webchanges](https://pypi.org/project/webchanges/), which reconstructs diffed data generated by html2text back into HTML.

**Comment by Alir3z4** [comment]
Sorry for delayed response.

It's all good, thanks.
Could you please resolve the conflict and I'll merge right away.

**Comment by mborsetti** [comment]
Thx, merge done

**Pull request merged**
