### PR TITLE
Docs, decode errors spelling mistake

### PR DESCRIPTION
**Pull request by theSage21**
change 

--decode_errors to --decode-errors

### CODE REVIEW

**Comment by Alir3z4** [comment]
Thanks, great.

Why https://travis-ci.org/Alir3z4/html2text/jobs/85055712 is failing, seems to be an issue with coveralls?

**Comment by theSage21** [comment]
Seems to be so. I will look into it.

**Comment by theSage21** [comment]
@Alir3z4 that fixes it. Using `coveralls==0.5` instead of coveralls in the `.travis.yml` you can merge now.

**Comment by Alir3z4** [comment]
@theSage21 Nice, I just merged into

**Pull request merged**
