### PR TITLE
Coverage detects tests carried out in subprocesses. Fix #71

### LINKED ISSUE #71: Coverage not detecting cmd line test execution
The coverage module is not detecting the command line tests due to them being carried out
in subprocesses.

Am I right in this?[Nedbat](http://nedbatchelder.com/code/coverage/subprocess.html) shows us how to do it but I am unable to implement it.

Fixing this would increase code coverage a lot as the cli.py file currently stands at 0% coverage.

I do not have experience with coverage.py and so it would take me a long time to fix.
@Alir3z4 @mcepl if you can fix this please do.

### PR DESCRIPTION
**Pull request by theSage21**
Earlier coverage was not detecting tests carried out in subprocesses. (the Command Line Tests)
This led to the coverage report for the module showing `html2text/cli.py` as 0% covered.

Fix for #71.

### CODE REVIEW

**Comment by theSage21** [comment]
Can someone help me figure out what is wrong?
```
export COVERAGE_PROCESS_START=$PWD/.coveragerc
coverage erase
PYTHONPATH=$PYTHONPATH:. coverage run --source=html2text setup.py test -v
coverage combine
coverage report
````
Running this on my machine shows 89% coverage but coveralls does not seem to pick it up.
I think I missed something in the .travis.yml file.

@Alir3z4

**Comment by Alir3z4** [comment]
@theSage21 I think it's coveralls itself, dig into coveralls documentation/service itself and see if you find something about it.

**Comment by theSage21** [comment]
@Alir3z4 The issue has been fixed for the past 3 commits. I was waiting for Coveralls to comment. The missing part was `coverage combine`. Based on [this](https://coveralls.io/r/Alir3z4/html2text) the coverage is now at 92%

**Comment by Alir3z4** [comment]
@theSage21 You've done a great work, amazing man.
Thank you so much ;)

**Pull request merged**
