### PR TITLE
Support Python 3.10, 3.11 and 3.12

### PR DESCRIPTION
**Pull request by mborsetti**
* Support Python 3.10 (edits to `.travis.yml`, `setup.cfg` and `tox.ini` files)

In the process of implementing the above, this fix was required:
* Fix test data for `br_inside_a` (my creation, not sure how this wrong version got pushed and passed Travis CI)
* Setting environment variable PYTHONUTF8 = 1 in `tox.ini` as Unicode tests would fail due to encoding defaulting to windows-1252 on Windows
* Added `.gitattribute` to have correct line endings

In the process of fixing the above, the following was discovered:
* Reversed order of arguments in assertions in tests (was `assert result == actual` but pytest standard -- and IDESs -- expect the reverse order, i.e. `assert actual == expected`)

In the process of all the above the following was in the way:
* Modern IDEs don't allow `*.md` files to end with multiple empty lines and will automatically trim them out, so I had to modify tests to `assert actual.rstrip() == expected.rstrip()`

All `tox` tests are passed by this PR.

### CODE REVIEW

**Comment by Alir3z4** [comment]
This is wonderful.

Unfortunately, I've noticed this pull request after https://github.com/Alir3z4/html2text/pull/358#issuecomment-1868045215 (_I reverted https://github.com/Alir3z4/html2text/pull/373 along the way to make the CI pass, please feel free to return it in this pull request if it won't cause CI failure_).

Could you please update the pull request?

**Comment by mborsetti** [comment]
> This is wonderful.
> 
> Unfortunately, I've noticed this pull request after [#358 (comment)](https://github.com/Alir3z4/html2text/pull/358#issuecomment-1868045215) (_I reverted #373 along the way to make the CI pass, please feel free to return it in this pull request if it won't cause CI failure_).
> 
> Could you please update the pull request?

What is the timeframe for a new release? 

I don't see this project as being maintained (its last [release ](https://pypi.org/project/html2text/) is practically 4 years old)

**Comment by Alir3z4** [comment]
I will be making a new release right after merging this pull request.

**Comment by mborsetti** [comment]
> I will be making a new release right after merging this pull request.

Sounds good.  I've updated the PR and it now supports Python 3.11 and 3.12 too.  Runs on local environment.

**Review by okiwan — APPROVED** [review]

**Comment by okiwan** [comment]
Thank you for this update. Coincidentally, this is happening at the right time for us so we can update our dependencies :-) Any plans merging this and creating the new release? Is there something can be done to help speeding this us?

**Pull request merged**
