### PR TITLE
Fix for issue where html entities got out of text.

### LINKED ISSUE #31: HTMl enities get out of anchor text
@szepeviktor:

another strange behaviour
```html
<a href="http://thth" class="nolink" style="text-decoration:none;color:inherit;cursor:default;">&#225;ll&#225;s: Country Manager</a>
```
```markdown
a[llas: Country Manager](http://thth)
```

### PR DESCRIPTION
**Pull request by theSage21**
Fixed #31 
Additions

- Tests
- Issue fix
- Coveragerc update to ignore some things

### CODE REVIEW

**Comment by Alir3z4** [comment]
@theSage21 Nice work, please update the changelog as well please.

**Comment by theSage21** [comment]
@Alir3z4 what version is this? 2015.6.12?
And I just have to mention the updates which are not there right?

**Comment by Alir3z4** [comment]
@theSage21 this one is the future version :D

You can initial a future release in changelog as below:

```
0000.0.0
=====
- - - -

Feature #ID: title and stuff
```

Leave the `zero`s as they're, whenever it's the time I'll change those tiny 0000 to date that I want to be published.

**Comment by theSage21** [comment]
@Alir3z4 please resolve the conflict, I do not want to clutter this PR with extra commits.

**Pull request merged**
