### PR TITLE
Add callback feature

### PR DESCRIPTION
**Pull request by critiqjo**
This PR enables finer-grained control over the output generated. Example usage:

```python
my_em = False
def my_tag_handle(parser, tag, attrs, start):
  global my_em
  if tag == 'em':
    if 'class' in attrs and 'my' in attrs['class'] and start:
      parser.o("[my] ")
      my_em = True
      return True
    elif my_em and not start:
      parser.o("[/my]")
      my_em = False
      return True

parser = html2text.HTML2Text()
parser.tag_callback = my_tag_handle
text = parser.handle(html)
```

### CODE REVIEW

**Comment by critiqjo** [comment]
It may not be handling the `google_doc` stuff properly... I haven't thoroughly gone through it... What do you think?

**Comment by theSage21** [comment]
Sounds good. You should fix the tests though. You thoughts @Alir3z4 ?

**Comment by critiqjo** [comment]
>You should fix the tests though.

If you're referring to this: https://travis-ci.org/Alir3z4/html2text/jobs/82910348
I don't see how it's related to the changes brought in this PR.

And I don't understand why [these 2 lines](https://coveralls.io/builds/3710037/source?filename=html2text%2F__init__.py#L286) are marked in red. Please explain...

As an aside, I also wanted to introduce 2 flags along with this:
1. `sink_output`: when true, all outputs are ignored, but input gets processed and tag callbacks are served.
2. `no_break`: when true, all line breaks are ignored. (useful in ignoring unnecessary line-breaks due to `<p>` tags inside `<td>`.)

A quick exploration did not give me any idea on how to go about this. May be I'll return to this later.

**Comment by theSage21** [comment]
- Marked lines.
    - `if internet_available:` is preferred over `if internet_available is True:`. 
    - I think that is why the lines are marked.
- I do believe that the recent releases of coverage4.0 and coveralls is what is causing the build to break. I am verifying it.

**Comment by Alir3z4** [comment]
Thanks for the patch, the callback feature is really nice. Like it so much.
As for the tests, I'll trigger the build myself again and look into it.

**Comment by Alir3z4** [comment]
@critiqjo Could you please follow this guidelines https://github.com/Alir3z4/html2text/blob/master/docs/contributing.md then I'll merge right away

**Comment by critiqjo** [comment]
> `if internet_available:` is preferred over `if internet_available is True:`

The latter is type sensitive, `if internet_available:` is "true" even if `internet_available = 10`...

I'm sorry, I'm not getting enough time to go through the test architecture and add them...

**Comment by theSage21** [comment]
@critiqjo sure it is, but that is the reason they are marked in red.

**Comment by theSage21** [comment]
@critiqjo could you push an empty commit? Coveralls was causing problems in the builds as seen in https://github.com/Alir3z4/html2text/pull/95. Can you trigger a build again?

**Comment by Alir3z4** [comment]
> @critiqjo could you push an empty commit? Coveralls was causing problems in the builds as seen in #95. Can you trigger a build again?

I don't think that will work, I just restart the build on travis, it failed.
@critiqjo need to first update with the latest from the master that includes  84e4bf2dd35e5ed14f5961b4d028a7af564c40d2.
No worries, I'll  merge this pull-request.

**Comment by critiqjo** [comment]
@theSage21 @Alir3z4 Done!

**Comment by Alir3z4** [comment]
@critiqjo Thanks for the nice feature, it's in the master now.
@theSage21 Thank you for your follow-up on this issue.

**Pull request merged**
