### PR TITLE
Fix for #136 and cleanup for #137

### PR DESCRIPTION
**Pull request by theSage21**

### CODE REVIEW

**Comment by theSage21** [comment]
Fixes #136  
Changelog entry for #137

**Comment by Alir3z4** [comment]
@theSage21 CI has failed on the tests for all the python versions, please have a look at https://travis-ci.org/Alir3z4/html2text/builds/143538474

overall, it looks good.

**Comment by theSage21** [comment]
I hate these backward compatibility forced options. Will fix in a while.

**Comment by theSage21** [comment]
@Alir3z4 that should fix things. Pull when ready.

**Pull request merged**
