### PR TITLE
Feature #164: Housekeeping: Add flake8 to the travis build, cleanup existing flake8 violations, add py3.6 and pypy3 to the travis build

### PR DESCRIPTION
**Pull request by ciprianmiclaus**

### CODE REVIEW

**Comment by ciprianmiclaus** [comment]
Do you want this change?

**Comment by Alir3z4** [comment]
> Do you want this change?

I don't know how I missed this, sorry.
Merging it right away.,

**Comment by ciprianmiclaus** [comment]
No worries, thanks for merging!

**Comment by Alir3z4** [comment]
@ciprianmiclaus I merged the changes and it seems the tests are failing now https://travis-ci.org/Alir3z4/html2text/builds/235775460

Can you please have a look ?

**Comment by ciprianmiclaus** [comment]
I'll look into the failing tests.

**Comment by ciprianmiclaus** [comment]
Can you re-trigger the build manually in Travis?
The errors seem spurious related to pip/setuptools on py3.2 and pypy3 - it might be a transient problem in Travis.
The build of my fork works fine in Travis for 3.2

**Comment by ciprianmiclaus** [comment]
Have you managed to re-trigger the build in Travis?
I forked the repo again, and my fork builds fine in Travis. So I suspect it was a one off problem in Travis.
A quick rebuild will confirm or deny that quickly.

**Comment by Alir3z4** [comment]
> Have you managed to re-trigger the build in Travis?

Sorry I'm on a bad connection these days.
Yes, I've triggered the build and the same error happened.

**Comment by ciprianmiclaus** [comment]
Sorry, I was busy in the last few days, but I'm still on this.
With your recent invite, hopefully I should be able to reproduce easily.

**Comment by Alir3z4** [comment]
Awesome, glad you can reproduce the issue.
Let me know if you need anything ;)

**Pull request merged**
