### PR TITLE
Support Python 3.5 (convert_charrefs=False)

### PR DESCRIPTION
**Pull request by stefanor**
We can't use the new default, until we stop supporting all versions of
Python that don't accept this argument (it appeared in 3.4)

Fixes: #89

### CODE REVIEW

**Comment by Alir3z4** [comment]
@stefanor So you think we would be better to drop python 3.4 completely ?

**Comment by stefanor** [comment]
The option I suggested was dropping everything before 3.4 (including 2.7). That's not really realistic, which is why I took the approach I took.

**Comment by Alir3z4** [comment]
@stefanor Ok, that make sense.
Could you please do the following changes https://github.com/Alir3z4/html2text/blob/master/docs/contributing.md so we can merge right away.

**Comment by stefanor** [comment]
Done.

**Comment by Alir3z4** [comment]
@stefanor it's in the master now.
Thank you for the great work

**Pull request merged**
