### PR TITLE
Adding tests for the module

### PR DESCRIPTION
**Pull request by theSage21**
Added more tests for the module.

### CODE REVIEW

**Comment by Alir3z4** [comment]
@theSage21 This is awesome.
Could you please update the docs and ``README.md`` for `--reference-links` flag? if you like to do it in another branch is fine by me.

**Comment by theSage21** [comment]
Ah yes. I had forgotten that. Thank you. Will do in just a minute.

**Comment by theSage21** [comment]
@Alir3z4 Done.

**Comment by Alir3z4** [comment]
@theSage21 Thanks for the great work.

As for #71 I'll look into it soon ;)

**Pull request merged**
